name: CI/CD Pipeline

on:
  push:
    paths:
      - 'index.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy index.html to CentOS7 Machine
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ./index.html abdulahad@192.168.181.130:/home/abdulahad/testing-ejm

          # Optional: Add any additional commands needed on your CentOS 7 machine after the file is copied
          # For example, you might restart a service or execute a script
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} abdulahad@192.168.181.130 'echo "File copied successfully!"'
